package:
  name: artiq-dev
  version: {{ environ["GIT_DESCRIBE_TAG"] }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ["GIT_DESCRIBE_NUMBER"] }}
  string: {{ environ["GIT_DESCRIBE_NUMBER"] }}+git{{ environ["GIT_FULL_HASH"][:8] }}

requirements:
  run:
    - python >=3.5.3,<3.6
    - setuptools 33.1.1
    - migen 0.7 py35_23+gitf4180e9
    - misoc 0.11 py35_3+git4c010df2
    - jesd204b 0.5
    - microscope
    - binutils-or1k-linux >=2.27
    - llvm-or1k 4.0.1
    - llvmlite-artiq 0.20.0
    - rust-core-or1k 1.23.0 19
    - openocd 0.10.0 6
    - lit
    - outputcheck
    - coverage
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - sphinx 1.4.8
    - sphinx-argparse
    - sphinxcontrib-wavedrom
    - sphinx_rtd_theme
    - h5py
    - python-dateutil
    - pyqt >=5.5
    - quamash
    - pyqtgraph 0.10.0
    - pygit2
    - aiohttp
    - pythonparser >=1.1
    - levenshtein

about:
  home: https://m-labs.hk/artiq
  license: LGPL
  summary: 'ARTIQ development metapackage'
