package:
  name: artiq
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}

requirements:
  build:
    - python >=3.5.2
    - setuptools
    - numpy
    - binutils-or1k-linux
  run:
    - python >=3.5.2
    - llvmlite-artiq 0.10.0.dev py35_24
    - lit
    - outputcheck
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - sphinx 1.4.8
    - sphinx-argparse
    - sphinxcontrib-wavedrom
    - sphinx_rtd_theme
    - h5py
    - dateutil
    - pyqt >=5.5
    - quamash
    - pyqtgraph
    - pygit2
    - aiohttp
    - binutils-or1k-linux
    - pythonparser
    - levenshtein

test:
  imports:
    - artiq

about:
  home: https://m-labs.hk/artiq
  license: GPL
  summary: 'ARTIQ (Advanced Real-Time Infrastructure for Quantum physics) is a next-generation control system for quantum information experiments. It is being developed in partnership with the Ion Storage Group at NIST, and its applicability reaches beyond ion trapping.'
