package:
  name: artiq
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_FULL_HASH", "")[:12] }}

requirements:
  build:
    - python 3.5.3
    - setuptools
  run:
    - python 3.5.3
    - llvmlite-artiq 0.12.0.dev py35_30
    - binutils-or1k-linux
    - pythonparser 1.0
    - openocd >=0.10
    - lit
    - outputcheck
    - scipy
    - numpy
    - prettytable
    - asyncserial
    - h5py
    - dateutil
    - pyqt >=5.5
    - quamash
    - pyqtgraph 0.10.0
    - pygit2
    - aiohttp
    - levenshtein

test:
  imports:
    - artiq

about:
  home: https://m-labs.hk/artiq
  license: GPL
  summary: 'ARTIQ (Advanced Real-Time Infrastructure for Quantum physics) is a next-generation control system for quantum information experiments. It is being developed in partnership with the Ion Storage Group at NIST, and its applicability reaches beyond ion trapping.'
