package:
  name: artiq-sayma_rtm
  version: {{ environ["GIT_DESCRIBE_TAG"] }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ["GIT_DESCRIBE_NUMBER"] }}
  string: {{ environ["GIT_DESCRIBE_NUMBER"] }}+git{{ environ["GIT_FULL_HASH"][:8] }}
  ignore_prefix_files: True

requirements:
  build:
    - artiq-dev {{ "{tag} {number}+git{hash}".format(tag=environ["GIT_DESCRIBE_TAG"], number=environ["GIT_DESCRIBE_NUMBER"], hash=environ["GIT_FULL_HASH"][:8]) }}
  run:
    - artiq {{ "{tag} {number}+git{hash}".format(tag=environ["GIT_DESCRIBE_TAG"], number=environ["GIT_DESCRIBE_NUMBER"], hash=environ["GIT_FULL_HASH"][:8]) }}

about:
  home: https://m-labs.hk/artiq
  license: LGPL
  summary: 'Bitstream and CSR map for Sayma RTM'
